### ISSUE TITLE
Startup issue

### ISSUE THREAD

**Issue by typicalsmc** [khoi3105/crawlscore#1]
Im getting this error on launch for some reason ? 

```DevTools listening on ws://127.0.0.1:53784/devtools/browser/3ddce099-d99b-437c-9113-c11f1c4cbde5
Traceback (most recent call last):
  File "D:\crawlscore-vietschool\crawl.py", line 128, in <module>
    start()
  File "D:\crawlscore-vietschool\crawl.py", line 38, in start
    checklist.click()
  File "C:\Users\typical\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\typical\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\typical\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "C:\Users\typical\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found in the current frame
  (Session info: chrome=131.0.6778.86); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
        GetHandleVerifier [0x00007FF69F4B6CB5+28821]
        (No symbol) [0x00007FF69F423840]
        (No symbol) [0x00007FF69F2C578A]
        (No symbol) [0x00007FF69F2CC2ED]
        (No symbol) [0x00007FF69F2CEFCC]
        (No symbol) [0x00007FF69F2CF09F]
        (No symbol) [0x00007FF69F31B34B]
        (No symbol) [0x00007FF69F30CA96]
        (No symbol) [0x00007FF69F33F2FA]
        (No symbol) [0x00007FF69F30C3F6]
        (No symbol) [0x00007FF69F33F510]
        (No symbol) [0x00007FF69F35F412]
        (No symbol) [0x00007FF69F33F0A3]
        (No symbol) [0x00007FF69F30A778]
        (No symbol) [0x00007FF69F30B8E1]
        GetHandleVerifier [0x00007FF69F7EFCAD+3408013]
        GetHandleVerifier [0x00007FF69F80741F+3504127]
        GetHandleVerifier [0x00007FF69F7FB5FD+3455453]
        GetHandleVerifier [0x00007FF69F57BDBB+835995]
        (No symbol) [0x00007FF69F42EB5F]
        (No symbol) [0x00007FF69F42A814]
        (No symbol) [0x00007FF69F42A9AD]
        (No symbol) [0x00007FF69F41A199]
        BaseThreadInitThunk [0x00007FFEC396DBE7+23]
        RtlUserThreadStart [0x00007FFEC559FBEC+44]
```

i got my chrome webdriver launched and vietschool website rendered then chrome just exit itself for some reason

**Comment by typicalsmc** [comment]
Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
Selenium version: 4.26.1

**Comment by typicalsmc** [comment]
resolved all on my fork https://github.com/TypicalShavonne/crawlscore
